### ISSUE TITLE
Unable to fetch proof parameter files

### ISSUE THREAD

**Issue by creativcoder** [ChainSafe/forest#2100]
**Describe the bug**

While running tests as part of https://github.com/ChainSafe/forest/pull/2084, there's a failing test `test_download_location_of_proof_parameter_files_default`: [Logs](https://github.com/ChainSafe/forest/actions/runs/3281359527/jobs/5403263893#step:6:155)

This is possibly another instance of: [2092](https://github.com/ChainSafe/forest/pull/2092)

**To Reproduce**

Pretty intermittent at this point. Will update soon on repro.

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```
---- test_download_location_of_proof_parameter_files_default stdout ----
thread 'test_download_location_of_proof_parameter_files_default' panicked at 'Unexpected failure.
code-101
stderr=```"thread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:thread \'6tokio-runtime-worker\' panicked at \'\ncalled `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'thread \'tokio-runtime-workertokio-runtime-worker\' panicked at \'\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', \', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs/home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs::181181::66\n\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'thread \'tokio-runtime-workertokio-runtime-worker\' panicked at \'\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', \', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs/home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs::181:181thread \'6:tokio-runtime-worker\n6\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\n\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-workerthread \'\' panicked at \'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\' panicked at \'\', called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }/home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs\', :/home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181181::66\n\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'tokio-runtime-worker\' panicked at \'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }\', /home/ubuntu/actions-runner/_work/forest/forest/utils/paramfetch/src/lib.rs:181:6\nthread \'main\' panicked at \'called `Result::unwrap()` on an `Err` value: Aggregated errors:\ntask 10 panicked\n\ntask 11 panicked\n\ntask 12 panicked\n\ntask 13 panicked\n\ntask 14 panicked\n\ntask 15 panicked\n\ntask 16 panicked\n\ntask 17 panicked\n\ntask 18 panicked\n\ntask 19 panicked\n\ntask 20 panicked\n\ntask 21 panicked\n\ntask 22 panicked\n\ntask 23 panicked\n\ntask 24 panicked\n\ntask 25 panicked\n\ntask 26 panicked\n\ntask 27 panicked\n\ntask 28 panicked\n\ntask 29 panicked\n\ntask 30 panicked\n\ntask 31 panicked\n\ntask 32 panicked\', forest/cli/src/cli/fetch_params_cmd.rs:44:14\n"```
  ```
</details> 

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
 - OS: 
 - Rust version(e.g. `rustc --version`): rustc 1.66.0-nightly (470e518c4 2022-09-27)
 - Branch/commit: creativcoder/tokio-tasks

**Other information and links**

**Comment by LesnyRumcajs** [comment]
I'm not sure if it is related but I got fiasco with proof parameters on `forest` startup just now.
```
 2022-10-20T16:02:36.139Z WARN  forest_paramfetch              > Error checking file: Checksum mismatch in param file "/volumes/forest_data/filecoin-proof-parameters/v28-fil-inner-product-v1.srs". (12bb3a5961507284fd42170e50f3d64d != ae20310138f5ba81451d723f858e3797)

```
using `forest-daemon 0.4.1+git.b007c3f`

**Comment by creativcoder** [comment]
I just check the [original source](https://raw.githubusercontent.com/filecoin-project/filecoin-ffi/master/parameters.json) of proof params and it seems to be missing `v28-fil-inner-product-v1.srs` which we seem to have in our `parameters.json`.

otoh, I also ran the test `test_download_location_of_proof_parameter_files_default` from main branch and it seems to be passing.
