### ISSUE TITLE
Error validating epoch 2695330

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2684]
**Describe the bug**

Forest crashes during validating epoch 2695330. The same error was reproduced on 2 machines

**To Reproduce** Steps to reproduce the behavior:

1. Run forest on mainnet

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```console
2023-03-20T11:22:17.623958Z  INFO forest_chain_sync::tipset_syncer: Validating tipset: EPOCH = 2695329, N blocks = 7    
2023-03-20T11:27:22.886552Z  INFO forest_chain_sync::tipset_syncer: Validating tipset: EPOCH = 2695330, N blocks = 3    
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `192`', /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bellperson-0.24.1/src/groth16/proof.rs:87:9
stack backtrace:
   0:     0x55fce8f013ca - std::backtrace_rs::backtrace::libunwind::trace::hb525d69e070ade81
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fce8f013ca - std::backtrace_rs::backtrace::trace_unsynchronized::hc013ba6c022c8cc0
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fce8f013ca - std::sys_common::backtrace::_print_fmt::hc99069d428720acc
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55fce8f013ca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6b2dfd5fb54878e3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fce8f2d5de - core::fmt::write::he277a08b33a83db8
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/fmt/mod.rs:1232:17
   5:     0x55fce8efce35 - std::io::Write::write_fmt::h6a5aa3320aae0280
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/io/mod.rs:1684:15
   6:     0x55fce8f01195 - std::sys_common::backtrace::_print::h763b5adb4e9083ff
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55fce8f01195 - std::sys_common::backtrace::print::h5a4028b32a3df8a2
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55fce8f028ef - std::panicking::default_hook::{{closure}}::h0c8c81b9641f8819
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:271:22
   9:     0x55fce8f0262b - std::panicking::default_hook::h5bf7cd33f355743b
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:290:9
  10:     0x55fce8f02e98 - std::panicking::rust_panic_with_hook::h11aed2986f5c5154
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:692:13
  11:     0x55fce8f02d99 - std::panicking::begin_panic_handler::{{closure}}::h5030a267c334a760
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:583:13
  12:     0x55fce8f01836 - std::sys_common::backtrace::__rust_end_short_backtrace::hf19b9029d2a05570
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55fce8f02aa2 - rust_begin_unwind
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:579:5
  14:     0x55fce4450d43 - core::panicking::panic_fmt::hc179041817e007c3
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/panicking.rs:64:14
  15:     0x55fce445107f - core::panicking::assert_failed_inner::h8126bd5f3b79de2a
  16:     0x55fce89369a8 - core::panicking::assert_failed::hc3dd90c0306d8971
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/panicking.rs:211:5
  17:     0x55fce879ba81 - bellperson::groth16::proof::Proof<E>::read_many::hd87bb86c9b78ebd5
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bellperson-0.24.1/src/groth16/proof.rs:87:9
  18:     0x55fce87a5eb3 - storage_proofs_core::multi_proof::MultiProof::new_from_bytes::hafba5300eb13b10a
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/storage-proofs-core-13.0.0/src/multi_proof.rs:48:22
  19:     0x55fce8501d0b - storage_proofs_core::multi_proof::MultiProof::new_from_reader::h56815b81ca1e26cb
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/storage-proofs-core-13.0.0/src/multi_proof.rs:37:9
  20:     0x55fce84ec9f7 - filecoin_proofs::api::window_post::verify_window_post::h01fc2f99a1ce489e
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/filecoin-proofs-13.0.0/src/api/window_post.rs:230:27
  21:     0x55fce8348357 - filecoin_proofs_api::post::verify_window_post_inner::h0bc2331f1e22cb01
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/filecoin-proofs-api-13.0.0/src/post.rs:574:20
  22:     0x55fce8347eda - filecoin_proofs_api::post::verify_window_post::h62db32ca0f632114
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/filecoin-proofs-api-13.0.0/src/post.rs:539:5
  23:     0x55fce6e1eb40 - fvm::kernel::default::verify_post::h88ee48fe118ad509
                               at /home/me/.cargo/git/checkouts/ref-fvm-114d9b36e8092399/8abb97b/fvm/src/kernel/default.rs:1190:5
  24:     0x55fce49e8d6c - <fvm::kernel::default::DefaultKernel<C> as fvm::kernel::CryptoOps>::verify_post::{{closure}}::h13273562035046ed
                               at /home/me/.cargo/git/checkouts/ref-fvm-114d9b36e8092399/8abb97b/fvm/src/kernel/default.rs:544:13
  25:     0x55fce44a56fd - std::panicking::try::do_call::h8403054a81fff506
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  26:     0x55fce44da05b - __rust_try
  27:     0x55fce448dfad - std::panicking::try::hee34ee738ab2e61f
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  28:     0x55fce53b6676 - std::panic::catch_unwind::hf85be2efa3d33f1c
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  29:     0x55fce49de4ff - fvm::kernel::default::catch_and_log_panic::hbaf2cc43ca122e12
                               at /home/me/.cargo/git/checkouts/ref-fvm-114d9b36e8092399/8abb97b/fvm/src/kernel/default.rs:1041:11
  30:     0x55fce49e8b12 - <fvm::kernel::default::DefaultKernel<C> as fvm::kernel::CryptoOps>::verify_post::h1a4f3530a5163b68
                               at /home/me/.cargo/git/checkouts/ref-fvm-114d9b36e8092399/8abb97b/fvm/src/kernel/default.rs:543:18
  31:     0x55fce48195d2 - fvm::syscalls::crypto::verify_post::h9482981b3289e265
                               at /home/me/.cargo/git/checkouts/ref-fvm-114d9b36e8092399/8abb97b/fvm/src/syscalls/crypto.rs:159:5
  32:     0x55fce46241c6 - core::ops::function::Fn::call::h2ce4355dcd25f8c9
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/ops/function.rs:79:5
  33:     0x55fce4fcb9a7 - <wasmtime::linker::Linker<fvm::syscalls::InvocationData<K>> as fvm::syscalls::bind::BindSyscall<(A,B),Ret,Func>>::bind::{{closure}}::h27d832538a684dac
                               at /home/me/.cargo/git/checkouts/ref-fvm-114d9b36e8092399/8abb97b/fvm/src/syscalls/bind.rs:170:44
  34:     0x55fce52cf789 - <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3),R>>::into_func::wasm_to_host_shim::{{closure}}::{{closure}}::h496f95410b1c4127
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func.rs:1851:41
  35:     0x55fce462b2c1 - core::ops::function::FnOnce::call_once::h178df9eb9a9dc323
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/ops/function.rs:250:5
  36:     0x55fce470f65c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfbd3a035a58dca8f
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/core/src/panic/unwind_safe.rs:271:9
  37:     0x55fce44b0a03 - std::panicking::try::do_call::hc37f5d24b48c3195
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:487:40
  38:     0x55fce44da05b - __rust_try
  39:     0x55fce4487699 - std::panicking::try::hcff541ef3f24d329
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panicking.rs:451:19
  40:     0x55fce53b460d - std::panic::catch_unwind::hb7a1f4b9a15e2ae4
                               at /rustc/1716932743a7b3705cbf0c34db0c4e070ed1930d/library/std/src/panic.rs:140:14
  41:     0x55fce52c66ed - <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3),R>>::into_func::wasm_to_host_shim::{{closure}}::h49ce565359ced5e3
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func.rs:1846:29
  42:     0x55fce5310698 - wasmtime::func::Caller<T>::with::hf621b141fac2b739
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func.rs:1648:9
  43:     0x55fce52c432f - <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3),R>>::into_func::wasm_to_host_shim::hb1524d5e5713248d
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func.rs:1835:34
  44:     0x75eddf10fc67 - <unknown>
  45:     0x75eddee0b8c9 - <unknown>
  46:     0x75eddefb6c4f - <unknown>
  47:     0x75eddf0c281a - <unknown>
  48:     0x75eddf23e3f6 - <unknown>
  49:     0x55fce47fd57b - <(A1,) as wasmtime::func::typed::WasmParams>::invoke::{{closure}}::hd075dfef56ef7c40
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func/typed.rs:582:21
  50:     0x55fce5301fb6 - <(A1,) as wasmtime::func::HostAbi>::call::h369039643037d165
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func.rs:1554:18
  51:     0x55fce47fd532 - <(A1,) as wasmtime::func::typed::WasmParams>::invoke::h81b99afcdc4a31ca
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func/typed.rs:580:17
  52:     0x55fce47ff16c - wasmtime::func::typed::TypedFunc<Params,Results>::call_raw::{{closure}}::h9f07006f7ffb5c2b
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-2.0.2/src/func/typed.rs:170:26
  53:     0x55fce4e073fb - wasmtime_runtime::traphandlers::catch_traps::call_closure::h75bde5692a969313
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-2.0.2/src/traphandlers.rs:204:18
  54:     0x55fce7fcb9a2 - wasmtime_setjmp
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-2.0.2/src/helpers.c:55:3
  55:     0x55fce4e08106 - wasmtime_runtime::traphandlers::catch_traps::{{closure}}::hb197682e89d11d1d
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-2.0.2/src/traphandlers.rs:186:9
  56:     0x55fce4e08182 - wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with::{{closure}}::h04f52659279e86f5
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-2.0.2/src/traphandlers.rs:370:44
  57:     0x55fce44eacef - wasmtime_runtime::traphandlers::tls::set::h0b89f87fac3c38b7
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-2.0.2/src/traphandlers.rs:627:13
  58:     0x55fce48ed91e - wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with::h4a1a692484060f06
                               at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-runtime-2.0.2/src/traphandlers.rs:370:19
  59:     0x55fce4e0782c - wasmtime_runtime::traphandlers::catch_traps::h42c67645d48300d0
                               at /home/me/.cargo/registry/s...
  ```
</details>

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**

- OS:
- Rust version(e.g. `rustc --version`)
- Branch/commit

**Other information and links**

**Comment by hanabi1224** [comment]
Tried upgrading `fvm@v2.2` to `fvm@v2.3`, still got the same error

**Comment by hanabi1224** [comment]
> @hanabi1224 It'd be great to include the debug (full debug) backtrace.

@LesnyRumcajs full debug backtrace updated

**Comment by lemmih** [comment]
Can be replicated with this snapshot: https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/historical/snapshot_2692800_2695690_1679453412.car.zst

This bug can be "fixed" by disabling abort-on-panic. The FVM (as part of `bellperson`) uses panics for error handling.
