### ISSUE TITLE
Panic in `MessagePool::select_messages_optimal`

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#4490]
## Describe the bug

Logic in `select_messages_optimal` is quite out-of-sync with lotus. We need to revisit and update the logic to get parity.

## To reproduce

1. Send the below payload to `http://localhost:2345/rpc/v0`
```
{"jsonrpc":"2.0","id":0,"method":"Filecoin.MpoolSelect","params":
[[{"/":"bafy2bzaceb6vn533luic5oo7tnvudxy2g7jusjc4m3egjb3ei3tu2lhmdlbvi"},{"/":"bafy2bzaceabqr4736hunl6wu36xs5yqwdjhwbopplwqxykf54ssgbaqaphsq4"},{"/":"bafy2bzacec7zaiykrnemfuqmed7pkiyranuhixkfbv6aaa6rvkwojya5opnuk"}],0.8]
}
```
2. get the below panic
```
thread 'tokio-runtime-worker' panicked at /home/me/git/forest/src/message_pool/msgpool/selection.rs:446:17:
attempt to subtract with overflow
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

forest code (panic in the last line):
```rust
                chains[i].merged = true;
                result.extend(chains[i].msgs.clone());
                random_count += chains[i].msgs.len();
                gas_limit -= chain_gas_limit;
```

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details>

## Environment (please complete the following information):

- OS:
- Branch/commit
- Hardware

**Comment by akaladarshi** [comment]
@hanabi1224 Can I pick this?

**Comment by akaladarshi** [comment]
@hanabi1224 For the request mentioned in the issue:

```
curl` -X POST http://127.0.0.1:2345/rpc/v0 -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":0,"method":"Filecoin.MpoolSelect","params":
[[{"/":"bafy2bzaceb6vn533luic5oo7tnvudxy2g7jusjc4m3egjb3ei3tu2lhmdlbvi"},{"/":"bafy2bzaceabqr4736hunl6wu36xs5yqwdjhwbopplwqxykf54ssgbaqaphsq4"},{"/":"bafy2bzacec7zaiykrnemfuqmed7pkiyranuhixkfbv6aaa6rvkwojya5opnuk"}],0.8]
}' 
```

getting response:
```
{"jsonrpc":"2.0","id":0,"error":{"code":-32603,"message":"Invalid tipset: no msg root with cid bafy2bzacedsj5rgmylcdddk2ctwifph2q6lwrxso26g4xrnxs45quzwfv63li"}}
```

**Comment by LesnyRumcajs** [comment]
@akaladarshi I believe you need to look for some more recent messages. The one mentioned in the issue is probably difficult to find now. Either this or you can try importing a snapshot that might have this particular message included. https://forest-archive.chainsafe.dev/list

**Comment by LesnyRumcajs** [comment]
@hanabi1224 can we replicate it still?

**Comment by LesnyRumcajs** [comment]
@hanabi1224 can we replicate it still?

**Comment by LesnyRumcajs** [comment]
@hanabi1224 can we replicate it still?

**Comment by LesnyRumcajs** [comment]
@hanabi1224 @akaladarshi Real-world reproducibility aside, can we just make sure this code cannot panic, i.e., all bounds are checked and overflow is not possible regardless of the input? It might be a good candidate for some `quicktest` tests.

**Comment by LesnyRumcajs** [comment]
Reproducible with recent epochs trying out multiple tipsets.

```console
❯ forest-cli chain head --format json -n 100 | ./mpool_select_killer.rb
/Users/rumcajs/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/http-5.3.1/lib/http/connection.rb:112:in 'HTTP::Connection#read_headers!': couldn't read response headers (HTTP::ResponseHeaderError)
```

the `mpool_select_killer.rb` being

```ruby
#!/usr/bin/env ruby

require 'json'
require 'http'

input = STDIN.read
data = JSON.parse(input)

data.map { |item| item['cids'].map { |cid| { '/' => cid } } }.each do |tipset|
  response = HTTP.post('http://localhost:2345/rpc/v0',
    headers: { 'Content-Type' => 'application/json' },
    json: {
      jsonrpc: '2.0',
      method: 'Filecoin.MpoolSelect',
      params: [tipset, 0.8],
      id: 1
    })
end
```

**Comment by LesnyRumcajs** [comment]
The panic might also happen in different place.

```console
thread 'tokio-runtime-worker' panicked at src/message_pool/msg_chain.rs:204:13:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'forest --chain calibnet --encry…' terminated by signal SIGABRT (Abort)
```

also

```console
thread 'tokio-runtime-worker' panicked at src/message_pool/msgpool/selection.rs:457:17:
```

**Comment by LesnyRumcajs** [comment]
It might not be everything, but Forest definitely lacks this logic https://github.com/filecoin-project/lotus/commit/ac3cdf75fa8e50ae61c3a7caf6473e2e38038f4d.
